language: rust
rust:
  - stable
env:
  - RUST_TEST_THREADS=1
addons:
  apt:
    packages:
      - binutils-dev
      - jackd
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libjack-dev
      - libjack0
before_install:
  - jackd -r -ddummy -r44100 -p1024 &
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=#HOME/.local:$PATH
  - cargo install cargo-travis -f
after_success:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - travis-cargo --only stable doc-upload
  - cargo coveralls
script:
  - travis-cargo test
  - travis-cargo doc -- -j 1
cache:
  bundler: true
  directories:
    - "$HOME/.cargo/"
