language: rust
env:
  global:
    - RUST_TEST_THREADS=1
  matrix:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job

addons:
  apt:
    packages:
      - jackd
      - libjack-dev
      - libjack0
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
before_install:
  - jackd -r -ddummy -r44100 -p1024 &
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=#HOME/.local:$PATH
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify
  - ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/jack*
script:
  - travis-cargo test
  - travis-cargo doc -- -j 1
cache:
  bundler: true
  directories:
    - "$HOME/.cargo/"
